### ISSUE TITLE
The [move-meta] [DOTX019W] error message should help identifying the topic

### ISSUE THREAD

**Issue by xephon2** [dita-ot/dita-ot#2724]
The log message `[DOTX019W]` currently looks like this:

```
[move-meta] [DOTX019W][WARN]: The type attribute on a topicref was set to 'xxxxx',
but the topicref references a 'yyyyy' topic.
This may cause your links to sort incorrectly in the output.
Note that the type attribute cascades in maps,
so the value 'xxxxx' may come from an ancestor topicref.
```

Unfortunately the message does not help to identify the `<topicref>`.

- [ ] I believe this to be a bug, not a question about using DITA-OT.
- [x] I read the [CONTRIBUTING][] file.

## Expected Behavior

The message should help the user to determine the affected `<topicref>`.

## Actual Behavior

Affected `<topicref>` is not reported.

## Possible Solution

The message should print the linking attributes `@href` and/or `@keyref`.

## Environment

* DITA-OT version: 2.5
* Operating system and version: all
* How did you run DITA-OT?
  
    - [ ] `dita` command
    - [x] Ant
    - [ ] `startcmd`
    - [ ] oXygen, other editor, CMS, etc.
* Transformation type _(HTML5, PDF, custom, etc.)_: all

[CONTRIBUTING]: https://github.com/dita-ot/dita-ot/blob/develop/.github/CONTRIBUTING.md

**Comment by jelovirt** [comment]
In addition to adding the source of the issue, the message itself should be shortened.

**Comment by xephon2** [comment]
Same problem for **[DOTX028E]**:

```
[topicpull] [DOTX028E][ERROR]: Link or cross reference must contain a valid href or keyref attribute; no link target is specified.
```

The message does not help to find the problem in the codebase.

**Comment by xephon2** [comment]
Same problem for **[DOTX072I]**

```
  [clean-map] [DOTX072I][INFO]: Ignoring navtitle within topicgroup.
```

The message does not help to find the problem in the codebase.

**Comment by drmacro** [comment]
Note that ignoring navtitles within topicgroup is behaving per spec so not an error and shouldn't be something that you would normally need to fix. Of course, not sure it's useful to report it either, since presumably the author put the navtitle on the topicgroup for a good reason (e.g., to label a group of key definitions).

**Comment by xephon2** [comment]
@drmacro I'd be fine with simply removing **[DOTX072I]**. But if it shouldn't, it should point to the affected map.

**Comment by drmacro** [comment]
I agree that any such message should point to the element to which it refers.
